# Generated by Django 2.2.10 on 2021-01-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210122_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
