# Generated by Django 2.2.10 on 2021-01-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210122_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='timestamp',
        ),
    ]
