# Generated by Django 2.2.10 on 2021-01-22 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_review_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='timestamp',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
