# Generated by Django 2.2.10 on 2021-01-22 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210122_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='session',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Идентиифкатор сессии'),
        ),
        migrations.AlterField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 13, 35, 52, 810919)),
        ),
    ]
