# Generated by Django 2.2.10 on 2021-02-01 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210122_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 23, 8, 58, 264243)),
        ),
    ]
