# Generated by Django 2.2.10 on 2021-01-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210122_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='Итоговая цена',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Пользователь',
        ),
    ]
